Django_website/Django_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # include the urls.py in music section, starting with music/
    url(r'^music/', include('music.urls')),
]

Django_website/music/urls.py
from django.conf.urls import url
from . import views


# using namespace, so that the html can get the below urls in the correct app/section
app_name = 'music'

urlpatterns = [
    # views.index means index function
    # ^ means start point $ means end point '^$' means nothing after 'music/'

    # music/
    url(r'^$', views.index, name='index'),

    # music/<album_id>/ identify integer   P followed by parameter that go to view.py  after that is reg-ex
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),

    # music/<album_id>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite"),

]

Django_website/music/models.py
from django.db import models


class Album(models.Model):
    # variable name must be the column name
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    # similar with toString(), also show in the admin interface
    def __str__(self):
        return self.artist + '-' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    # similar with toString(), also show in the admin interface
    def __str__(self):
        return self.song_title

Django_website/music/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album

'''
# This method should add --- from django.template import loader
def index(request):
    # get all the records in the album table
    all_ablum = Album.objects.all()

    # serching the file under the templates folder
    template = loader.get_template('music/index.html')

    # add data/parameter to index.html
    context = {
        'all_album': all_ablum,
    }

    # pass the data set above
    return HttpResponse(template.render(context, request))
    '''


# the second method (using shortcut), clean code  --- from django.shortcuts import render
def index(request):
    all_ablum = Album.objects.all()
    context = {
        'all_album': all_ablum,
    }
    return render(request, 'music/index.html', context)

    '''
    # html code is nested with python code, which is not recommended.
    html = ""
    for album in all_ablum:
        # url not add "music/" at beginning. relative path
        url = str(album.id) + "/"
        html += '<a href="' + url + '">' + album.album_title + '</a><br>'

    return HttpResponse(html)
    '''


def detail(request, album_id):
    # deal with 404 error
    '''
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("album not exit")
    '''
    # using following codes to replace the above one

    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

    # return HttpResponse("<h2>" + album_id + "</h2>")


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        # according to the value of radio(song) to get song object
        select_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You didn't select valid song",
        })
    else:
        select_song.is_favorite = True
        select_song.save()
        return render(request, 'music/detail.html', {'album': album})

Django_website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <!-- bookstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "music/bootstrap.css" %}"/>
    <!-- add the font -->
    <link href="http://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- input css files -->
    <!-- css files below would overlap the bootstraps reference above -->
    <link rel="stylesheet" type="text/css" href="{% static "music/style.css" %}"/>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">HOME PAGE</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Song
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true">&nbsp;Add Album</span>
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true">&nbsp;Logout</span>
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

Django_website/music/templates/music/detail.html
{%  extends "music/base.html" %}

<!-- customization refer to different pages -->
{% block title%}Detail Page{% endblock %}


{% block body %}
<img src="{{album.album_logo }}">
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }}-{{ song.file_type }}</li>
    {% endfor %}
</ul>

<!-- add a form with raido -->

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
      <label for="song{{ forloop.counter }}">
          {{ song.song_title }}
          {% if song.is_favorite %}
              <img src="http://i.imgur.com/b9b13Rd.png"/>
          {% endif %}
      </label><br/>
    {% endfor %}
   <input type="submit" value="favorite">
</form>
{% endblock %}

Django_website/music/templates/music/favorite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

Django_website/music/templates/music/index.html
{%  extends "music/base.html" %}

{% block title%}Home Page{% endblock %}


{% block body %}
{% if all_album %}
    <ul>
        {% for album in all_album %}
            <!--<li><a href="/music/{{ album.id }}/">{{ album.album_title }}</a></li> -->
            <!-- using namespace and get url from url.py-->
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have album</h3>
{% endif %}
{% endblock %}